#!/bin/bash

# Set paths for the PDF.js build and target directories
PDFJS_BUILD=./pdfjs/pdf.js/build/generic
PDFJS_MINIFIED_BUILD=./pdfjs/pdf.js/build/minified
BUILD_BASE=./build

# Move into the PDF.js directory, install dependencies, and build
pushd pdfjs/pdf.js
npm ci
npx gulp generic
if [[ $PDFJS_CONFIG = "web" || $PDFJS_CONFIG = "all" ]]; then
	npx gulp minified
fi
popd

if [[ $PDFJS_CONFIG = "dev" || $PDFJS_CONFIG = "all" ]]; then
	# Set up directories for dev build
	BUILD=dev
	BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
	rm -rf "$BUILD_DIR"
	mkdir -p "$BUILD_DIR/build"
	mkdir -p "$BUILD_DIR/web/images"
	cp -r "$PDFJS_BUILD/LICENSE" "$BUILD_DIR/"
	cp -r "$PDFJS_BUILD/build/pdf.mjs" "$BUILD_DIR/build/"
	cp -r "$PDFJS_BUILD/build/pdf.worker.mjs" "$BUILD_DIR/build/"
	cp -r "$PDFJS_BUILD/web/cmaps" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/standard_fonts" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/iccs" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/wasm" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/viewer.html" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/viewer.mjs" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/images/loading-icon.gif" "$BUILD_DIR/web/images/"
	cp -r "pdfjs/viewer.css" "$BUILD_DIR/web/"
fi

if [[ $PDFJS_CONFIG = "web" || $PDFJS_CONFIG = "all" ]]; then
	# Set up directories for web build
	BUILD=web
	BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
	rm -rf "$BUILD_DIR"
	mkdir -p "$BUILD_DIR/build"
	mkdir -p "$BUILD_DIR/web/images"
	cp -r "$PDFJS_BUILD/LICENSE" "$BUILD_DIR/"
	cp -r "$PDFJS_MINIFIED_BUILD/build/pdf.min.mjs" "$BUILD_DIR/build/pdf.mjs"
	cp -r "$PDFJS_MINIFIED_BUILD/build/pdf.worker.min.mjs" "$BUILD_DIR/build/pdf.worker.mjs"
	cp -r "$PDFJS_BUILD/web/cmaps" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/standard_fonts" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/iccs" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/wasm" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/viewer.html" "$BUILD_DIR/web/"
	npx terser "$PDFJS_BUILD/web/viewer.mjs" -o "$BUILD_DIR/web/viewer.mjs"
	cp -r "$PDFJS_BUILD/web/images/loading-icon.gif" "$BUILD_DIR/web/images/"
	cp -r "pdfjs/viewer.css" "$BUILD_DIR/web/"
fi

if [[ $PDFJS_CONFIG = "zotero" || $PDFJS_CONFIG = "all" ]]; then
	# Set up directories for zotero build
	BUILD=zotero
	BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
	rm -rf "$BUILD_DIR"
	mkdir -p "$BUILD_DIR/build"
	mkdir -p "$BUILD_DIR/web/images"
	cp -r "$PDFJS_BUILD/LICENSE" "$BUILD_DIR/"
	cp -r "$PDFJS_BUILD/build/pdf.mjs" "$BUILD_DIR/build/"
	cp -r "$PDFJS_BUILD/build/pdf.worker.mjs" "$BUILD_DIR/build/"
	cp -r "$PDFJS_BUILD/web/cmaps" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/standard_fonts" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/iccs" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/wasm" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/viewer.html" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/viewer.mjs" "$BUILD_DIR/web/"
	cp -r "$PDFJS_BUILD/web/images/loading-icon.gif" "$BUILD_DIR/web/images/"
	cp -r "pdfjs/viewer.css" "$BUILD_DIR/web/"
fi
