#!/bin/bash

cd pdf.js
npm ci --legacy-peer-deps
npx gulp generic
cd ..

mkdir -p build/dev
cp -r pdf.js/build/generic/web/* build/dev/
cp -r pdf.js/build/generic/build/* build/dev/
cp -r pdf.js/build/generic/LICENSE build/dev/

mkdir -p build/web
cp -r pdf.js/build/generic/web/* build/web/
cp -r pdf.js/build/generic/build/* build/web/
cp -r pdf.js/build/generic/LICENSE build/web/

mkdir -p build/zotero
cp -r pdf.js/build/generic/web/* build/zotero/
cp -r pdf.js/build/generic/build/* build/zotero/
cp -r pdf.js/build/generic/LICENSE build/zotero/
rm build/zotero/*.pdf
rm build/zotero/*.map

node ./scripts/tweak-viewer-html.js
