#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PDFJS_DIR=pdf.js

cd "$PDFJS_DIR"
npm ci
# TODO: Use `generic` build for the web version
# npx gulp generic
# Zotero with FF 60 ESR runs only the `es5` build
npx gulp generic-es5
cd "$SCRIPT_DIR/../"

mkdir -p build/web
cp -r "$PDFJS_DIR"/build/generic-es5/web/* build/web/
cp -r "$PDFJS_DIR"/build/generic-es5/build/* build/web/
cp -r "$PDFJS_DIR"/build/generic-es5/LICENSE build/web/

mkdir -p build/zotero
cp -r "$PDFJS_DIR"/build/generic-es5/web/* build/zotero/
cp -r "$PDFJS_DIR"/build/generic-es5/build/* build/zotero/
cp -r "$PDFJS_DIR"/build/generic-es5/LICENSE build/zotero/
rm build/zotero/*.pdf

node ./scripts/tweak-viewer-html.js
