#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PDFJS_DIR=pdf.js

cd "$PDFJS_DIR"
npm ci
# TODO: Use `generic` build for the web version
# npx gulp generic
# Zotero with FF 60 ESR runs only the `legacy` build
npx gulp generic-legacy
cd "$SCRIPT_DIR/../"

mkdir -p build/web
cp -r "$PDFJS_DIR"/build/generic-legacy/web/* build/web/
cp -r "$PDFJS_DIR"/build/generic-legacy/build/* build/web/
cp -r "$PDFJS_DIR"/build/generic-legacy/LICENSE build/web/

mkdir -p build/zotero
cp -r "$PDFJS_DIR"/build/generic-legacy/web/* build/zotero/
cp -r "$PDFJS_DIR"/build/generic-legacy/build/* build/zotero/
cp -r "$PDFJS_DIR"/build/generic-legacy/LICENSE build/zotero/
rm build/zotero/*.pdf
rm build/zotero/*.map

node ./scripts/tweak-viewer-html.js
