#!/bin/bash
npm i
cd pdf.js
npm i
# in production use the `generic` build 
# npx gulp generic
npx gulp generic-es5
cd ..

mkdir -p build/web
cp -r pdf.js/build/generic-es5/web/* build/web/
cp -r pdf.js/build/generic-es5/build/* build/web/
cp -r pdf.js/build/generic-es5/LICENSE build/web/

mkdir -p build/zotero
cp -r pdf.js/build/generic-es5/web/* build/zotero/
cp -r pdf.js/build/generic-es5/build/* build/zotero/
cp -r pdf.js/build/generic-es5/LICENSE build/zotero/
rm build/zotero/*.pdf

node scripts/modify_viewer.js
